export const mockJobs = [
    {
      id: 1,
      title: "Senior Training Specialist",
      company: "EduTech Solutions",
      location: "New York, NY",
      type: "Full-time",
      experience: "3-5 years",
      salary: "$70,000 - $90,000",
      category: "Corporate Training",
      description: "Join our team to develop and deliver high-impact training programs for Fortune 500 clients.",
      extendedDescription: "As a Senior Training Specialist, you will be responsible for designing, developing, and delivering training programs for our corporate clients. You will work closely with subject matter experts to create engaging and effective learning experiences.\n\nThis role requires a mix of instructional design expertise, facilitation skills, and project management abilities.",
      postedDate: "2023-11-01",
      deadline: "2023-12-15",
      startDate: "2024-01-15",
      applications: 78,
      featured: true,
      logo: "https://randomuser.me/api/portraits/lego/1.jpg",
      requirements: [
        "Bachelor's degree in Education, Instructional Design, or related field",
        "3-5 years of experience in corporate training or adult education",
        "Proficiency in instructional design methodologies",
        "Experience with learning management systems (LMS)",
        "Strong presentation and facilitation skills",
        "Excellent communication and interpersonal abilities"
      ],
      responsibilities: [
        "Design and develop training materials including instructor guides, participant workbooks, and job aids",
        "Facilitate virtual and in-person training sessions",
        "Evaluate training effectiveness and make continuous improvements",
        "Collaborate with subject matter experts to create accurate and relevant content",
        "Stay current with training trends and best practices",
        "Track and report on training metrics"
      ],
      benefits: [
        "Comprehensive health insurance",
        "401(k) matching",
        "Professional development opportunities",
        "Flexible work arrangements",
        "Paid time off and holidays"
      ]
    },
    {
      id: 2,
      title: "E-Learning Instructional Designer",
      company: "LearnSphere",
      location: "Remote",
      type: "Remote",
      experience: "2-4 years",
      salary: "$65,000 - $85,000",
      category: "Instructional Design",
      description: "Create engaging online learning experiences using cutting-edge tools and methodologies.",
      extendedDescription: "As an E-Learning Instructional Designer, you will design and develop interactive and engaging online learning experiences. You will collaborate with subject matter experts to translate complex information into user-friendly digital learning content.\n\nThe ideal candidate has a strong background in instructional design theories, experience with e-learning authoring tools, and a portfolio demonstrating creative approaches to digital learning.",
      postedDate: "2023-11-10",
      deadline: "2023-12-20",
      startDate: "2024-01-10",
      applications: 54,
      featured: false,
      logo: "https://randomuser.me/api/portraits/lego/2.jpg",
      requirements: [
        "Bachelor's degree in Instructional Design, Educational Technology, or related field",
        "2-4 years of experience in e-learning content development",
        "Proficiency in e-learning authoring tools (Articulate Storyline, Captivate, etc.)",
        "Knowledge of learning theories and instructional design models",
        "Excellent writing and storyboarding skills",
        "Basic graphic design and multimedia skills"
      ],
      responsibilities: [
        "Design and develop engaging e-learning modules using industry standard tools",
        "Collaborate with subject matter experts to create accurate and meaningful content",
        "Apply adult learning principles to digital learning experiences",
        "Create assessments that effectively measure learning outcomes",
        "Ensure courses meet accessibility standards",
        "Stay current with e-learning trends and technologies"
      ],
      benefits: [
        "Fully remote position",
        "Flexible working hours",
        "Equipment stipend",
        "Professional development allowance",
        "Comprehensive benefits package"
      ]
    },
    {
      id: 3,
      title: "Learning Experience Designer",
      company: "InnovatEd",
      location: "San Francisco, CA",
      type: "Full-time",
      experience: "4-6 years",
      salary: "$90,000 - $120,000",
      category: "Learning Design",
      description: "Design innovative learning experiences that transform how people learn in digital environments.",
      extendedDescription: "As a Learning Experience Designer, you will create innovative learning experiences that blend the best of instructional design with UX design principles. You'll work with cross-functional teams to develop cutting-edge digital learning solutions that engage learners and drive measurable outcomes.\n\nThis role requires a creative mindset, technical aptitude, and a passion for transforming how people learn.",
      postedDate: "2023-11-15",
      deadline: "2023-12-30",
      startDate: "2024-02-01",
      applications: 42,
      featured: true,
      logo: "https://randomuser.me/api/portraits/lego/3.jpg",
      requirements: [
        "Bachelor's or Master's degree in Instructional Design, UX Design, or related field",
        "4-6 years of experience designing digital learning experiences",
        "Portfolio demonstrating innovative approaches to learning design",
        "Experience with learning experience platforms and authoring tools",
        "Understanding of user-centered design principles",
        "Knowledge of learning sciences and cognitive psychology"
      ],
      responsibilities: [
        "Design and develop innovative learning experiences for digital platforms",
        "Create user journeys and learning paths that engage and motivate learners",
        "Incorporate gamification and interactive elements to enhance engagement",
        "Collaborate with developers, graphic designers, and content experts",
        "Conduct user research and testing to inform design decisions",
        "Analyze learning data to continuously improve experiences"
      ],
      benefits: [
        "Competitive salary and equity options",
        "Premium health, dental, and vision insurance",
        "Unlimited PTO policy",
        "Learning stipend for professional development",
        "Onsite gym and wellness programs",
        "Catered lunches and snacks"
      ]
    },
    {
      id: 4,
      title: "Training Coordinator",
      company: "Global Learning Initiative",
      location: "Chicago, IL",
      type: "Part-time",
      experience: "1-2 years",
      salary: "$40,000 - $50,000",
      category: "Training Administration",
      description: "Coordinate and support the logistics of our corporate training programs across multiple locations.",
      extendedDescription: "As a Training Coordinator, you will provide administrative and logistical support for our training department. You will be responsible for scheduling sessions, managing registrations, preparing materials, and ensuring smooth operations of all training activities.\n\nThis role is ideal for a detail-oriented individual who excels at organization and enjoys supporting learning initiatives.",
      postedDate: "2023-11-20",
      deadline: "2023-12-15",
      startDate: "2024-01-05",
      applications: 32,
      featured: false,
      logo: "https://randomuser.me/api/portraits/lego/4.jpg",
      requirements: [
        "Associate's or Bachelor's degree (preferred)",
        "1-2 years of experience in administrative or coordinator roles",
        "Excellent organizational and time management skills",
        "Proficiency with MS Office and learning management systems",
        "Strong attention to detail",
        "Excellent communication skills"
      ],
      responsibilities: [
        "Schedule and coordinate training sessions across multiple locations",
        "Manage participant registrations and communications",
        "Prepare and distribute training materials",
        "Set up training venues and equipment",
        "Maintain accurate training records and generate reports",
        "Provide administrative support to the training team"
      ],
      benefits: [
        "Flexible part-time schedule",
        "Paid time off",
        "Professional development opportunities",
        "Potential for advancement to full-time role",
        "Collaborative team environment"
      ]
    },
    {
      id: 5,
      title: "Learning & Development Manager",
      company: "TechCorp Industries",
      location: "Austin, TX",
      type: "Full-time",
      experience: "5-7 years",
      salary: "$100,000 - $130,000",
      category: "L&D Management",
      description: "Lead our L&D team to design and implement comprehensive employee development programs.",
      extendedDescription: "As the Learning & Development Manager, you will oversee our company's training and development initiatives. You will lead a team of L&D professionals to create and implement learning strategies that support our business objectives and enhance employee performance.\n\nThis strategic role requires a combination of leadership skills, L&D expertise, and business acumen.",
      postedDate: "2023-11-05",
      deadline: "2023-12-20",
      startDate: "2024-01-15",
      applications: 25,
      featured: true,
      logo: "https://randomuser.me/api/portraits/lego/5.jpg",
      requirements: [
        "Bachelor's degree in HR, Education, or related field (Master's preferred)",
        "5-7 years of progressive experience in L&D roles",
        "Previous team management experience",
        "Strong understanding of adult learning principles",
        "Experience designing comprehensive learning strategies",
        "Excellent project management and budgeting skills"
      ],
      responsibilities: [
        "Develop and implement learning strategies aligned with business objectives",
        "Lead a team of instructional designers and training specialists",
        "Manage the L&D budget and resource allocation",
        "Evaluate the effectiveness of learning programs and initiatives",
        "Partner with department leaders to identify training needs",
        "Stay current with industry trends and best practices in L&D"
      ],
      benefits: [
        "Competitive salary and annual bonus",
        "Comprehensive benefits package",
        "Leadership development opportunities",
        "Generous 401(k) matching",
        "Flexible work arrangements",
        "Relocation assistance available"
      ]
    },
    {
      id: 6,
      title: "Educational Content Developer",
      company: "LearnWave Academy",
      location: "Boston, MA",
      type: "Contract",
      experience: "2-3 years",
      salary: "$60 - $75 per hour",
      category: "Content Development",
      description: "Create engaging educational content for our online learning platform focused on technology skills.",
      extendedDescription: "As an Educational Content Developer, you will create comprehensive learning materials for our online courses. You will work with subject matter experts to develop content that is accurate, engaging, and effective for diverse learners.\n\nThis contract position requires expertise in educational content development, with a focus on technology-related subjects.",
      postedDate: "2023-11-12",
      deadline: "2023-12-10",
      startDate: "2024-01-05",
      applications: 48,
      featured: false,
      logo: "https://randomuser.me/api/portraits/lego/6.jpg",
      requirements: [
        "Bachelor's degree in Education, Technical Writing, or relevant field",
        "2-3 years of experience developing educational content",
        "Strong writing and editing skills",
        "Knowledge of instructional design principles",
        "Familiarity with technology subjects (programming, data science, etc.)",
        "Experience with content management systems"
      ],
      responsibilities: [
        "Develop comprehensive course content including lessons, examples, and exercises",
        "Collaborate with subject matter experts to ensure technical accuracy",
        "Create clear explanations of complex technical concepts",
        "Develop assessments that effectively measure learning outcomes",
        "Review and revise content based on feedback",
        "Ensure consistent style and quality across course materials"
      ],
      benefits: [
        "Competitive hourly rate",
        "Flexible work schedule",
        "Remote work options",
        "Potential for long-term contract renewal",
        "Opportunity to work on cutting-edge technology courses"
      ]
    },
    {
      id: 7,
      title: "Virtual Classroom Facilitator",
      company: "Digital Learning Partners",
      location: "Remote",
      type: "Part-time",
      experience: "3+ years",
      salary: "$45 - $55 per hour",
      category: "Training Delivery",
      description: "Facilitate engaging virtual training sessions for corporate clients across various industries.",
      extendedDescription: "As a Virtual Classroom Facilitator, you will deliver live online training sessions using virtual classroom platforms. You will create engaging learning environments that promote participation and knowledge retention.\n\nThis role requires excellent facilitation skills, technical comfort with virtual platforms, and the ability to adapt to different audiences and subject matters.",
      postedDate: "2023-11-18",
      deadline: "2023-12-15",
      startDate: "2024-01-10",
      applications: 36,
      featured: false,
      logo: "https://randomuser.me/api/portraits/lego/7.jpg",
      requirements: [
        "Bachelor's degree in Education, Communication, or related field",
        "3+ years of experience facilitating training (virtual experience preferred)",
        "Proficiency with virtual classroom platforms (Zoom, MS Teams, WebEx, etc.)",
        "Strong presentation and public speaking skills",
        "Ability to engage remote participants effectively",
        "Excellent troubleshooting skills for technical issues"
      ],
      responsibilities: [
        "Deliver engaging virtual training sessions on various topics",
        "Create interactive learning environments that encourage participation",
        "Adapt delivery style to meet the needs of different audiences",
        "Manage the technical aspects of virtual classroom sessions",
        "Gather and respond to participant feedback",
        "Collaborate with instructional designers to improve course content"
      ],
      benefits: [
        "Flexible part-time schedule",
        "Work from anywhere",
        "Paid training for virtual facilitation skills",
        "Opportunity to work with diverse clients",
        "Potential for increased hours based on performance"
      ]
    },
    {
      id: 8,
      title: "Curriculum Development Specialist",
      company: "EdTech Innovations",
      location: "Seattle, WA",
      type: "Full-time",
      experience: "4-6 years",
      salary: "$75,000 - $95,000",
      category: "Curriculum Design",
      description: "Design comprehensive curricula for K-12 students integrating technology and innovative teaching methods.",
      extendedDescription: "As a Curriculum Development Specialist, you will design and develop comprehensive educational curricula for K-12 students. You will integrate technology and innovative teaching methods to create engaging learning experiences aligned with educational standards.\n\nThis role requires a deep understanding of curriculum design principles, educational technology, and K-12 education.",
      postedDate: "2023-11-08",
      deadline: "2023-12-15",
      startDate: "2024-01-20",
      applications: 29,
      featured: true,
      logo: "https://randomuser.me/api/portraits/lego/8.jpg",
      requirements: [
        "Bachelor's or Master's degree in Education, Curriculum Development, or related field",
        "4-6 years of experience in curriculum design for K-12 education",
        "Knowledge of educational standards and frameworks",
        "Experience integrating technology into curriculum",
        "Strong instructional design skills",
        "Excellent writing and content organization abilities"
      ],
      responsibilities: [
        "Design comprehensive curricula aligned with educational standards",
        "Develop lesson plans, activities, and assessments",
        "Integrate technology tools and digital resources into curriculum",
        "Collaborate with educators to test and refine materials",
        "Create teacher guides and implementation resources",
        "Stay current with educational research and best practices"
      ],
      benefits: [
        "Competitive salary and benefits package",
        "Generous paid time off",
        "Professional development opportunities",
        "Collaborative team environment",
        "Flexible work arrangements",
        "Education reimbursement program"
      ]
    },
    {
      id: 9,
      title: "LMS Administrator",
      company: "Enterprise Training Solutions",
      location: "Denver, CO",
      type: "Full-time",
      experience: "2-4 years",
      salary: "$65,000 - $80,000",
      category: "Learning Technology",
      description: "Manage and optimize our learning management system to support enterprise-wide training initiatives.",
      extendedDescription: "As an LMS Administrator, you will be responsible for managing and optimizing our learning management system. You will configure the system, manage user accounts, troubleshoot technical issues, and generate reports to support our enterprise-wide training initiatives.\n\nThis role requires technical expertise with learning management systems and a customer service mindset.",
      postedDate: "2023-11-15",
      deadline: "2023-12-20",
      startDate: "2024-01-15",
      applications: 39,
      featured: false,
      logo: "https://randomuser.me/api/portraits/lego/0.jpg",
      requirements: [
        "Bachelor's degree in IT, Educational Technology, or related field",
        "2-4 years of experience administering learning management systems",
        "Technical knowledge of LMS configuration and maintenance",
        "Experience with data management and reporting",
        "Problem-solving skills for troubleshooting issues",
        "Strong communication skills for working with users of all technical levels"
      ],
      responsibilities: [
        "Administer and maintain the learning management system",
        "Create and manage user accounts and permissions",
        "Configure courses, learning paths, and certifications",
        "Troubleshoot technical issues and provide user support",
        "Generate reports on training completion and effectiveness",
        "Implement system updates and new features"
      ],
      benefits: [
        "Comprehensive health and retirement benefits",
        "Paid time off and holidays",
        "Professional development opportunities",
        "Casual work environment",
        "Flexible schedule options",
        "Annual performance bonus"
      ]
    },
    {
      id: 10,
      title: "Training Needs Analyst",
      company: "Global HR Consultants",
      location: "Virtual",
      type: "Contract",
      experience: "3-5 years",
      salary: "$70 - $85 per hour",
      category: "Training Analysis",
      description: "Analyze organizational training needs and develop targeted learning strategies to address skill gaps.",
      extendedDescription: "As a Training Needs Analyst, you will assess organizational training requirements through comprehensive analysis. You will identify skill gaps, determine learning objectives, and recommend appropriate training solutions to improve employee performance and organizational effectiveness.\n\nThis contract position requires expertise in training needs assessment methodologies and a strategic approach to learning solutions.",
      postedDate: "2023-11-14",
      deadline: "2023-12-15",
      startDate: "2024-01-10",
      applications: 27,
      featured: false,
      logo: "https://randomuser.me/api/portraits/lego/1.jpg",
      requirements: [
        "Bachelor's degree in HR, Organizational Development, or related field",
        "3-5 years of experience in training needs analysis or organizational development",
        "Knowledge of needs assessment methodologies",
        "Experience with data collection and analysis",
        "Strong interviewing and facilitation skills",
        "Excellent communication and reporting abilities"
      ],
      responsibilities: [
        "Conduct comprehensive training needs assessments for client organizations",
        "Design and implement data collection methods (surveys, interviews, focus groups)",
        "Analyze performance data to identify skill and knowledge gaps",
        "Develop learning objectives based on identified needs",
        "Recommend appropriate training and development solutions",
        "Present findings and recommendations to stakeholders"
      ],
      benefits: [
        "Competitive hourly rate",
        "Virtual work environment",
        "Flexible schedule",
        "Networking opportunities with global clients",
        "Potential for contract extension or future projects"
      ]
    },
    {
      id: 11,
      title: "Gamification Learning Designer",
      company: "PlayLearn Education",
      location: "Los Angeles, CA",
      type: "Full-time",
      experience: "3-5 years",
      salary: "$85,000 - $110,000",
      category: "Learning Design",
      description: "Design innovative game-based learning experiences that transform traditional training into engaging journeys.",
      extendedDescription: "As a Gamification Learning Designer, you will create innovative learning experiences that incorporate game mechanics and principles. You will transform traditional training content into engaging, interactive journeys that motivate learners and improve knowledge retention.\n\nThis role requires a creative mindset, understanding of game design principles, and expertise in learning design.",
      postedDate: "2023-11-10",
      deadline: "2023-12-15",
      startDate: "2024-01-10",
      applications: 52,
      featured: true,
      logo: "https://randomuser.me/api/portraits/lego/2.jpg",
      requirements: [
        "Bachelor's degree in Instructional Design, Game Design, or related field",
        "3-5 years of experience designing learning experiences",
        "Knowledge of gamification principles and mechanics",
        "Experience with game-based learning platforms or tools",
        "Understanding of adult learning theories",
        "Creative problem-solving abilities"
      ],
      responsibilities: [
        "Design learning experiences that incorporate game mechanics and principles",
        "Transform traditional content into engaging game-based learning",
        "Create reward systems and progress tracking mechanisms",
        "Develop narratives and scenarios that engage learners",
        "Collaborate with subject matter experts to ensure content accuracy",
        "Test and iterate designs based on user feedback"
      ],
      benefits: [
        "Competitive salary and annual bonus",
        "Comprehensive benefits package",
        "Creative work environment",
        "Latest technology and tools",
        "Professional development budget",
        "Flexible work arrangements"
      ]
    },
    {
      id: 12,
      title: "Learning Analytics Specialist",
      company: "DataLearn Technologies",
      location: "Remote",
      type: "Full-time",
      experience: "4-6 years",
      salary: "$90,000 - $115,000",
      category: "Learning Analytics",
      description: "Leverage data analytics to measure learning effectiveness and drive continuous improvement of training programs.",
      extendedDescription: "As a Learning Analytics Specialist, you will collect, analyze, and interpret data related to learning and training activities. You will develop dashboards and reports that provide insights into learning effectiveness, and make recommendations for program improvements based on data analysis.\n\nThis role requires a combination of data analysis skills, instructional design knowledge, and business acumen.",
      postedDate: "2023-11-05",
      deadline: "2023-12-10",
      startDate: "2024-01-15",
      applications: 35,
      featured: false,
      logo: "https://randomuser.me/api/portraits/lego/3.jpg",
      requirements: [
        "Bachelor's degree in Data Science, Analytics, or related field",
        "4-6 years of experience in data analysis, preferably in L&D context",
        "Proficiency with data analysis tools and techniques",
        "Experience creating data visualizations and dashboards",
        "Understanding of learning measurement methodologies",
        "Strong problem-solving and critical thinking skills"
      ],
      responsibilities: [
        "Design and implement learning measurement strategies",
        "Collect and analyze data related to learning activities",
        "Develop dashboards and reports that visualize learning data",
        "Identify trends and patterns in learning effectiveness",
        "Make data-driven recommendations for program improvements",
        "Communicate analytics insights to stakeholders"
      ],
      benefits: [
        "Competitive salary",
        "Remote work environment",
        "Comprehensive benefits package",
        "Professional development opportunities",
        "Latest analytics tools and technologies",
        "Flexible work schedule"
      ]
    }
  ];